spring.application.name=pacer
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=false

cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}
